dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-prepare_ceph_adm
    image: RHEL-7.6-Server-x86_64-production-latest
    flavor: m1.small
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
    cleanup: ../shared/cleanup.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  enabled: false
